# This file was generated by GoReleaser. DO NOT EDIT.
class Wwhrd < Formula
  desc "Have Henry Rollins check vendored licenses in your Go project."
  homepage "https://github.com/frapposelli/wwhrd/blob/master/README.md"
  version "0.2.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/frapposelli/wwhrd/releases/download/v0.2.4/wwhrd_0.2.4_darwin_amd64.tar.gz"
    sha256 "8268c69e07dfd961faf1c73e2acc692777029eb656bb4ef61789c5d201af9cf5"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/frapposelli/wwhrd/releases/download/v0.2.4/wwhrd_0.2.4_linux_amd64.tar.gz"
      sha256 "cf3cd7c913a73ba088629b953c55c82a875a76165d779b4b39d35b16bbb2f0ed"
    end
  end

  def install
    bin.install "wwhrd"
  end

  test do
    system "#{bin}/wwhrd -v"
  end
end
