# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wwhrd < Formula
  desc "Have Henry Rollins check vendor licenses in your Go project"
  homepage "https://github.com/frapposelli/wwhrd/blob/master/README.md"
  version "0.4.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/frapposelli/wwhrd/releases/download/v0.4.0/wwhrd_0.4.0_darwin_amd64.tar.gz"
    sha256 "05863867ae4e724148daf94183724606dff080c5d5b52e502a504181c131777e"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/frapposelli/wwhrd/releases/download/v0.4.0/wwhrd_0.4.0_linux_amd64.tar.gz"
    sha256 "59aa6f71c6d71f3780e76a8baaf8c1070dbd4c15b86cac6704e3e14da3d95af6"
  end

  def install
    bin.install "wwhrd"
  end

  test do
    system "#{bin}/wwhrd -v"
  end
end
